print("Please enter a character for Beep's eyes.")
eyes = input()
# Dixplay a box
print("  ###########################")
print(" #                           #")
print(" #      ###############      #")
print("#   ####               ####    #")
print("#  #  -" + eyes + "-    #####   -" + eyes + "-   #   #")
print("#   #########     #########    #")
print("#                             #")
print(" #                           #")
print("  ############   ############ ")
print ("            #   #")
print("        ###############")
print("       #################")
print("       ######## ########")
print("       #######   #######")
print("       ###### -0- ######")
print("       ###### -1- ######")
print("       #######   #######")
print("       ######## ########")
print("       #################")
print("        ###############")
print("         #############")
print("          ###########")
print("            #######")
print("              ###")
