# Display escape / special characters
print(" First line")
print("\n Displays a new line")
print("\t Displays a tab space")
print("\\ Displays a back slash")
print("\" Displays a double quote")
print("\' Displays a single quote")
print("\n")
print("\t I am Beep!")
print("\n")